project:
  type: website
  output-dir: docs

website:
  title: "Saber Pro Unal"
  search: 
    location: navbar
    type: overlay
  navbar:
    left:
      - href: index.qmd
        text: Contexto
      - href: Descriptiva.qmd
        text: Descriptiva
      - href: ACP.qmd
        text: ACP
      - href: ACS.qmd
        text: ACS
      - href: ACM.qmd
        text: ACM
      

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    toc: true

editor: visual



