---
title: "Saber Pro Unal"
format: html
engine: knitr
---

## **Introducción**

El presente análisis estadístico aborda la prueba Saber Pro aplicada a estudiantes de la Universidad Nacional de Colombia durante el año 2018. Este examen constituye un instrumento estandarizado vital para la evaluación externa de la calidad de la educación superior en el país. La evaluación abarca cinco competencias fundamentales: lectura crítica, razonamiento cuantitativo, competencias ciudadanas, comunicación escrita e inglés. Además, incluye módulos de competencias específicas que varían según el grupo de referencia al que pertenezca el programa académico del estudiante.

## **Planteamiento del Problema de Investigación**

El objetivo principal de este análisis es examinar si las condiciones socioeconómicas de los estudiantes inciden en sus resultados obtenidos en la prueba Saber Pro.

## **Marco Conceptual**

Basándonos en datos proporcionados por el DANE y el ICFES sobre la calidad educativa y el rendimiento de los estudiantes en esta evaluación, se analizarán los resultados de los estudiantes de la Universidad Nacional de Colombia junto con su información socioeconómica relevante.

## **Objetivos**

1.  Determinar si las diversas variables socioeconómicas influyen en los puntajes obtenidos en el Saber Pro.

2.  Evaluar el rendimiento general de los puntajes por facultades.

3.  Identificar los componentes de la prueba en los que los estudiantes de la Universidad Nacional de Colombia destacan.

## **Justificación**

La importancia de este análisis radica en la necesidad de divulgar los resultados de la prueba, identificar áreas de mejora para los estudiantes y explorar posibles vínculos entre las condiciones socioeconómicas y el rendimiento académico. Esta información puede servir de base para desarrollar estrategias que promuevan mejores resultados académicos en el futuro.

## **Metodología**

Inicialmente, se llevará a cabo un estudio descriptivo univariado, seguido de un análisis de la relación entre las variables para obtener una visión más amplia del objeto de estudio. Posteriormente, se implementará un análisis de componentes principales (ACP) para profundizar en la comprensión de los datos.

**Tipos de Variables**

*Categóricas:*

-   Facultades

-   Programa Académico

-   Género

-   Pago de matrícula por parte de los padres

-   Edad (rangos)

-   Nivel educativo familiar

-   Valor de la matrícula

-   Horas de trabajo semanal

-   Estrato socioeconómico

*Cuantitativas:*

-   Razonamiento Cuantitativo

-   Comunicación Escrita

-   Lectura Crítica

-   Competencia Ciudadana

-   Inglés

-   Puntaje Global

## Bibliografía

-   <https://www.datos.gov.co/Educaci-n/Resultados-nicos-Saber-Pro/u37r-hjmu/about_data>

-   <https://www.dane.gov.co/index.php/estadisticas-por-tema/educacion>
